/**
 * What a child process is allowed to do, and how that gets onto its command
 * line.
 *
 * Subagents are default-deny: a child runs with `--no-extensions`, an explicit
 * `--tools` allowlist, and one `-e` per extension backing an allowed tool. The
 * consequence worth knowing is quiet — a tool named in `--tools` but backed by
 * no `-e` simply does not exist in the child, with nothing said about it — so
 * the tool-to-extension map and the allowlist have to agree, and they are kept
 * in one place for that reason.
 *
 * `sandboxArgs` is the single source of truth for reconstructing a sandbox. Both
 * the initial launch and the resume path go through it so the two can never
 * drift. It returns arguments rather than mutating a caller's array, so a test
 * can assert on a result without building a container for it first.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { getAgentConfigDir } from "./agents.ts";
import type { SubagentLoadout } from "./session.ts";
import { shellEscape } from "./tmux.ts";

const EXTENSION_DIR = dirname(fileURLToPath(import.meta.url));
const SIBLING_EXTENSIONS_DIR = resolve(EXTENSION_DIR, "..");

/**
 * Tools registered by index.ts. Granting any of them is what pulls the
 * orchestration extension into a child, which is why `send_message` is
 * deliberately NOT here: every subagent gets it, and mapping it to that file
 * would load the whole extension — widget, watchers, status timers — into every
 * leaf. It lives in SUBAGENT_CONTROL_TOOLS instead, backed by subagent-done.ts,
 * which every subagent already loads.
 */
export const SPAWNING_TOOLS = ["subagent", "subagents_list"] as const;

/**
 * Tools every subagent keeps regardless of how tightly its role restricts tools.
 * Backed by subagent-done.ts, which is loaded into every subagent session, so
 * granting these never widens which extensions a child loads.
 */
export const SUBAGENT_CONTROL_TOOLS = ["send_message"] as const;

/**
 * Tools from the codebase-memory-mcp wrapper (`<agentDir>/extensions/cbmem.ts`).
 * The file is generated by that project's installer, so it is listed here
 * rather than expected to register itself.
 */
const CBMEM_TOOLS = [
  "index_repository",
  "search_graph",
  "query_graph",
  "trace_path",
  "get_code_snippet",
  "get_graph_schema",
  "get_architecture",
  "search_code",
  "list_projects",
  "delete_project",
  "index_status",
  "check_index_coverage",
  "detect_changes",
  "manage_adr",
  "ingest_traces",
] as const;

/** Built-in tools pi provides natively — no extension needs to be loaded. */
const BUILTIN_TOOLS = new Set(["read", "write", "edit", "bash", "grep", "find", "ls"]);

/**
 * A filename-safe slug of a display name, for the artifact and script files
 * named after a subagent. `fallback` covers a name with no usable characters
 * at all (e.g. one that is entirely punctuation or CJK).
 *
 * It lives here because every file named after a subagent is a launch artifact,
 * and this module is where a launch is assembled.
 */
export function slugify(name: string, fallback = "subagent") {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return slug || fallback;
}

/**
 * Map a custom (non-built-in) tool name to the pi-extension file that
 * registers it. Used to build the child's `--extension` whitelist after
 * `--no-extensions` disables global discovery. Returns undefined for built-in
 * tools and for unknown names (which simply won't be granted).
 */
export function getToolExtensionPath(tool: string): string | undefined {
  if (BUILTIN_TOOLS.has(tool)) return undefined;
  // The spawning tools are registered by index.ts. Naming it explicitly rather
  // than using import.meta.url, which would resolve to this file instead.
  if ((SPAWNING_TOOLS as readonly string[]).includes(tool)) {
    return join(EXTENSION_DIR, "index.ts");
  }
  if (tool === "safe_bash") {
    const safeBash = join(EXTENSION_DIR, "tools", "safe-bash.ts");
    return existsSync(safeBash) ? safeBash : undefined;
  }
  const map: Record<string, readonly string[]> = {
    web_search: ["web-search", "index.ts"],
    web_fetch: ["web-fetch", "index.ts"],
    video_extract: ["video-extract", "index.ts"],
    youtube_search: ["youtube-search", "index.ts"],
    google_image_search: ["google-image-search", "index.ts"],
    // codebase-memory-mcp's knowledge-graph tools, all from one flat file.
    // Mapped here so a child that is GRANTED one actually gets it: the child
    // runs with --no-extensions, so a tool named in --tools but backed by no
    // -e simply does not exist, with nothing said about it. Mapping every tool
    // is not granting them — that is each agent role's `tools:` field.
    ...Object.fromEntries(CBMEM_TOOLS.map((tool) => [tool, ["cbmem.ts"]])),
  };
  // This extension is not necessarily installed under ~/.pi/agent. When it is
  // vendored into a config repo the extensions backing these tools sit beside
  // it, so look where this file actually lives before the agent dir.
  const segments = map[tool];
  if (segments) {
    for (const base of [SIBLING_EXTENSIONS_DIR, join(getAgentConfigDir(), "extensions")]) {
      const candidate = join(base, ...segments);
      if (existsSync(candidate)) return candidate;
    }
  }
  return undefined;
}

/**
 * Build the child's `--tools` allowlist, or null to pass no restriction at all.
 *
 * pi applies `--tools` to built-in, extension and custom tools alike, so a role
 * that restricts itself to e.g. "read,bash,write" would otherwise hide the
 * control tools and leave a resumed or user-touched subagent unable to call
 * send_message. Those are added unconditionally; the spawning tools only on an
 * explicit grant.
 */
export function computeToolAllowlist(
  effectiveTools: string | undefined,
  opts: { grantSpawning: boolean },
) {
  const requested = (effectiveTools ?? "")
    .split(",")
    .map((tool) => tool.trim())
    .filter(Boolean);

  // No explicit tool restriction and no spawning grant → don't pass --tools at
  // all (the child keeps its default toolset).
  if (requested.length === 0 && !opts.grantSpawning) return null;

  const allow = new Set(requested);
  if (opts.grantSpawning) {
    for (const tool of SPAWNING_TOOLS) allow.add(tool);
  }
  for (const tool of SUBAGENT_CONTROL_TOOLS) {
    allow.add(tool);
  }

  return [...allow].join(",");
}

/**
 * The command-line arguments that reconstruct a loadout's sandbox: model,
 * identity (written to a file under `artifactDir/context`), and the
 * default-deny tool/extension restriction.
 *
 * Env vars (PI_SUBAGENT_AGENT / PI_SUBAGENT_ALLOWED / PI_CODING_AGENT_DIR) and
 * cwd stay the caller's responsibility, since they differ between launch and
 * resume. A null `toolAllowlist` means the spawn was intentionally unrestricted
 * (e.g. a fork clone) and is replayed as-is.
 */
export function sandboxArgs(
  loadout: SubagentLoadout,
  opts: { artifactDir: string; name: string },
) {
  const parts: string[] = [];

  if (loadout.model) {
    const model = loadout.thinking ? `${loadout.model}:${loadout.thinking}` : loadout.model;
    parts.push("--model", shellEscape(model));
  }

  if (loadout.identity) {
    const flag =
      loadout.systemPromptMode === "replace" ? "--system-prompt" : "--append-system-prompt";
    const spTimestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
    const spPath = join(
      opts.artifactDir,
      `context/${slugify(opts.name)}-sysprompt-${spTimestamp}.md`,
    );
    mkdirSync(dirname(spPath), { recursive: true });
    writeFileSync(spPath, loadout.identity, "utf8");
    parts.push(flag, shellEscape(spPath));
  }

  // Default-deny: disable global extension discovery and re-enable only the
  // extensions backing the whitelisted tools.
  if (loadout.toolAllowlist) {
    parts.push("--no-extensions");
    parts.push("--tools", shellEscape(loadout.toolAllowlist));

    const extPaths = new Set<string>();
    for (const tool of loadout.toolAllowlist.split(",")) {
      const extPath = getToolExtensionPath(tool);
      if (extPath && existsSync(extPath)) extPaths.add(extPath);
    }
    for (const extPath of extPaths) {
      parts.push("-e", shellEscape(extPath));
    }
  }

  return parts;
}

/**
 * Build the positional prompt args for a Pi CLI subagent launch.
 *
 * In artifact-backed launches (lineage-only, standalone), Pi's
 * buildInitialMessage() concatenates @file content with messages[0] into one
 * initial prompt. That breaks /skill: expansion because the message no longer
 * starts with "/skill:". Only messages[1..] are sent as separate follow-up
 * prompts where /skill: is recognized. So when there are skill prompts AND
 * artifact-backed delivery, prepend an empty first positional message to push
 * the skill prompts into messages[1..].
 */
export function promptArgs(params: {
  effectiveSkills?: string;
  taskDelivery: "direct" | "artifact";
  taskArg: string;
}): string[] {
  const skillPrompts = (params.effectiveSkills ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)
    .map((skill) => `/skill:${skill}`);

  const needsSeparator = params.taskDelivery === "artifact" && skillPrompts.length > 0;

  return [...(needsSeparator ? [""] : []), ...skillPrompts, params.taskArg];
}
